### ISSUE TITLE
On code quality & nbproject

### ISSUE THREAD

**Issue by Zethson** [laminlabs/nbproject#156]
From the text: 

> Low code quality: A rigorous notebook publishing process encourages small modular notebooks with most code residing in versioned packages.

What if nbproject also more tightly integrated with pre-commit in any way? -> Track if a pre-commit setup has been run on the notebook. You could also provide some useful pre-commit setups that work well for notebooks. Some tools such as black work for them.

BTW, I think that your answer here is cheap and rarely reflects the true state :) For things to improve they have to be `enforced` such as done by e.g. pre-commit which nags you until you fix things. I'd argue that in most projects encouragement is not enough. As it is, I don't see a substantial contribution of nbproject to code quality. It has other strengths.

**Comment by Zethson** [comment]
I'll close this since it slightly deviates from the whole purpose of nbproject. Don't think that it's worthwhile atm to pick up the pre-commit idea from above.

**Comment by falexwolf** [comment]
Agreed.

This would be something that these days, we'd try to enforce with quality tags and corresponding policies on the db-level. You'd get warnings or errors upon interacting with the data lake through a notebook that doesn't fulfill standards.

But while it might sound easy, it's complicated in a number of ways and will only be feasible much further down the road.
