### ISSUE TITLE
Trying out nbproject on SaturnCloud

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/nbproject#231]
A first try to run nbproject on Saturn Cloud: https://saturncloud.io/

I started Jupyter Lab server and pip-installed from within the notebook

<img width="392" alt="image" src="https://user-images.githubusercontent.com/16916678/189680694-cfbf9063-0244-46ff-86ee-c45283fc6925.png">

After re-starting and re-executing the header, I get this

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/16916678/189680646-25d073a9-430a-49b3-882e-a89eafd4fd9a.png">

Hence, I install

<img width="390" alt="image" src="https://user-images.githubusercontent.com/16916678/189680870-e1f068ba-593c-465b-8e24-c01631c6dbf8.png">

After that, I get this dialogue

<img width="383" alt="image" src="https://user-images.githubusercontent.com/16916678/189681031-078d7f37-c5ee-4566-93fb-9da7fa6683c0.png">

It doesn't end up in writing the header, as usual. It seems to miss interactivity. Reverting (loading from disk) manually brings back the header.

<img width="399" alt="image" src="https://user-images.githubusercontent.com/16916678/189681261-d510433d-6884-4245-8648-74d54e3191ee.png">

Similar for the publish workflow. It works without interactivity but doesn't warn about it. 😔 

<img width="499" alt="image" src="https://user-images.githubusercontent.com/16916678/189681718-e95352e6-be77-4b66-98e3-55dbdf812227.png">

**Comment by Koncopd** [comment]
Thank for checking, i will investigate.
