### ISSUE TITLE
nbproject is causing weird cell shifts in vertex notebooks

### ISSUE THREAD

**Issue by ricomnl** [laminlabs/nbproject#233]
I noticed that since installing `nbproject` I get these weird shifts in my jupyter cells (using google vertex)

<img width="781" alt="Screen Shot 2022-09-19 at 21 20 55" src="https://user-images.githubusercontent.com/31646044/191324132-42db4bb7-de0f-4383-a75b-22298e4709e9.png">

**Comment by Koncopd** [comment]
Hi, @ricomnl , thanks for reporting. When does it happen?

**Comment by ricomnl** [comment]
I just noticed the same behavior in a separate session where `nbproject` was not installed so its not caused by it. I apologize for the preliminary conclusion :S
