### ISSUE TITLE
VS Code integration stopped working

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/nbproject#259]
https://laminlabs.slack.com/archives/C04FPE8V01W/p1681707692447649

**Comment by falexwolf** [comment]
**Getting filepath through a global VS Code variable**

So, VS Code seems friendly enough to expose this variable:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/16916678/232415820-4c527f05-08e2-48a9-ae57-c716509ef496.png">

However, the variable does not seem to be available from within 
<img width="596" alt="image" src="https://user-images.githubusercontent.com/16916678/232415917-1e93a219-b975-4112-a7b2-a29891749b35.png">

I'm astonished if this ever worked before

**Comment by falexwolf** [comment]
**Getting filepath through servers**

A year ago, I wrote this tiny adoption for VS Code. I don't think the Jupyter integration runs any jupyter server anymore, so, I think we can remove this piece fo code:
https://github.com/laminlabs/nbproject/blob/71693f9f493ca6738b3de253c7acb75249c3a3bd/nbproject/dev/_jupyter_communicate.py#L130-L138

**Comment by falexwolf** [comment]
Accessing the Jupyter notebook filename through the global variable seems to be officially supported: https://github.com/microsoft/vscode-jupyter/pull/8531

**Comment by Koncopd** [comment]
I am really surprised that the global variable way that i added some time ago fails.

**Comment by falexwolf** [comment]
Pasting from the vscode-jupyter PR above, it's evident that ClearML also has a notebook tracking feature that we can likely get inspiration from, if we ever want to!

> Following the discussion on https://github.com/microsoft/vscode-jupyter/issues/8475 , and mostly thanks to the great guidance of @rchiodo , this PR updates __vsc_ipynb_file__ global variable with the current jupyter filename. This enables [ClearML](https://github.com/allegroai/clearml/) to log the content of the jupyter notebook along side the outputs automagically :)

**Comment by falexwolf** [comment]
> I am really surprised that the global variable way that i added some time ago fails.

I think the variable is robust in the notebook itself, but I don't think it was ever defined in the global namespace of `_jupyter_communicate.py`. Do you think so?

**Comment by Koncopd** [comment]
Hm, so it should be probably accessed through code executed in kernel... I need to check that.

**Comment by Koncopd** [comment]
Ref https://github.com/microsoft/vscode-jupyter/issues/8475

**Comment by falexwolf** [comment]
Your issue is perfect and is the one that underlies the PR I linked! They're doing something similar than nbproject, just that ClearML does a lot more - it's very cool! :)

**Comment by falexwolf** [comment]
They have a lot of logic for inferring the filename, and we can adopt some of it, I guess (need to check the license, but given nbproject is open-source, too, it should be fine even if it's more restrictive)

https://github.com/allegroai/clearml/blob/2f4f11aadbcce198a0dca215cb901153a9ff86b6/clearml/backend_interface/task/repo/scriptinfo.py#L572-L776

**Comment by falexwolf** [comment]
@Koncopd, if you're free, could you push a fix based on the line of code shared above? Otherwise, no worries, I'll do it later today!

**Comment by Koncopd** [comment]
I will add.
