### ISSUE TITLE
Single line markdown titles not recognized in notebooks when running through PyCharm

### ISSUE THREAD

**Issue by ap--** [laminlabs/nbproject#285]
When running jupyter through PyCharm, adding a single line markdown cell with a title produces the following code in the ipynb file:

```json
{
 "cells": [
  {
   "metadata": {},
   "cell_type": "markdown",
   "source": "# My custom title",
   "id": "dfac67e992ee5bb6"
  }
 ]
}
```

`nbproject` is then unable to detect the notebook title, which consequently makes `ln.track` fail.

Culprit is the following code:

https://github.com/laminlabs/nbproject/blob/c28c19b7814d9fb6ad8eea63732cb20d884cc5eb/nbproject/dev/_meta_live.py#L20-L27

Which assumes that `"source"` is a list of lines of text. (PyCharm correctly produces a list of strings for multiline markdown cells)

Replacing `text = cell["source"][0]` with:

```python
   source = cell["source"]
   if isinstance(source, str):
       source = [source]
   text = source[0]
```

should restore correct behavior. Although to me the entire code block looks like initially it was meant to loop through all lines in the source. Maybe something like the following is more appropriate:

```python
   source = cell["source"]
   if isinstance(source, str):
       source = [source]
   for text in source:
       for line in text.splitlines():
           if line.lstrip().startswith("# "):
                ...
```

**Comment by Koncopd** [comment]
This was fixed by https://github.com/laminlabs/nbproject/pull/286
